const Project = [
    {
        id: "11",
        title: "React Financial Advisors Platform",
        slug: "financialadvisorplatform",
        image: '/images/Projects/financialadvisorplatform.png',
        technology: "React, TypeScript, Tailwind CSS, React Hook Form, TanStack Query/Table, Charting for advisor analytics",
        preview_url: "",
        short_description: `Built a web-based frontend interface for advisors and administrators, delivering profile management, onboarding workflows, and dashboards that provide clear lead visibility and performance insights. The UI was implemented using React, TypeScript, and Tailwind CSS, with emphasis on usability, scalability, and data clarity for daily operations.`,
    },
    {
        id: "12",
        title: "Mortgage CRM",
        slug: "mortgagecrm",
        image: '/images/Projects/mortgagecrm.png',
        technology: "React, TypeScript, Tailwind CSS",
        preview_url: "",
        short_description: `Built a CRM frontend interface used daily by a broker team to manage leads, collect documents, and follow recommended follow-ups with minimal manual effort. The user interface was implemented using React, TypeScript, and Tailwind CSS, with a strong focus on workflow efficiency, clarity, and auditability.`,
    },
    {
        id: "13",
        title: "Crypto iGaming Platform",
        slug: "cryptoigamingplatform",
        image: '/images/Projects/cryptoigamingplatform.png',
        technology: "React, TypeScript, Tailwind CSS, TanStack Query, TanStack Table, React Hook Form, Recharts/ECharts",
        preview_url: "",
        short_description: `Built frontend interfaces for a crypto iGaming platform using React, TypeScript, and Next.js, delivering both user-facing application flows and admin / backoffice tooling used daily by support and operations teams. The UI was designed for high data throughput, real-time visibility, and operational reliability, with styling implemented in Tailwind CSS.`,
    },
    {
        id: "1",
        title: "Adola AI",
        slug: "adolaai",
        image: '/images/Projects/adolaai.png',
        technology: "React.js, Node.js, LLM, OpenAI API, Prompt Engineering, TypeScript, TailwindCSS, PostgreSQL, Docker",
        preview_url: "https://adola.ai/",
        short_description: `Adola transforms telephony by integrating AI voice assistants with phone systems. Adola offers AI assistants for various businesses like restaurants, dentists, mechanics, barbershops, lawyers, doctors, construction, and general service. It also provides outbound call services for surveys, lead qualification, and event promotion.`,
    },
    {
        id: "6",
        title: "TrendMonster",
        slug: "trendmonster",
        image: '/images/Projects/trendmonster.png',
        technology: "Next.js, TradingView, Flask, Fred API, Redis, Stripe, Docker, AWS",
        preview_url: "https://trend.goatacademy.org/",
        short_description: `This platform documents a live experiment using a proprietary trading methodology developed by experienced market practitioners, emphasizing transparency by showing real-time signals, trades, and outcomes. TrendMonster is not investment advice or a managed fund; rather, it serves as a learning tool and demonstration of a systematic approach to capturing market trends and managing risk.`,
    },
    {
        id: "2",
        title: "Trip Tile",
        slug: "triptile",
        image: '/images/Projects/triptile.png',
        technology: "React.js, Node.js, Third-party API integration, Maps APIs, Stripe",
        preview_url: "https://www.triptile.com/",
        short_description: `Online travel planning and booking platform that helps users design personalized multi-city itineraries and book travel arrangements in one place. The service lets travelers choose destinations, hotels, activities, and transportation to build custom trips across regions like Europe, Asia, and the Americas.`,
    },
    {
        id: "3",
        title: "Telegram Bots AI",
        slug: "telegrambotsai",
        image: '/images/Projects/telegrambot.png',
        technology: "Telegram, Telegram API, ChatGPT, Python, Bot, LLaMA,",
        preview_url: "https://www.telegrambots.ai/",
        short_description: `These bots leverage advanced AI models to provide intelligent responses, assist with queries, and create engaging content seamlessly within Telegram chats.
        Users can ask questions, get suggestions, or even automate task assignments without leaving their conversation threads, enhancing productivity.`,
    },
    {
        id: "4",
        title: "Infinity Nail Spa & Salon",
        slug: "infinitytopeka",
        image: '/images/Projects/infinitytopeka.png',
        technology: "WordPress, SimpyBook.me, Divi, MySQL, Google Maps",
        preview_url: "https://www.infinitytopeka.com/",
        short_description: `The site is structured to clearly present service offerings, pricing information, and contact details, while enabling online appointment booking to streamline the customer journey. This platform emphasizes usability, responsive design, and conversion-focused layout to drive bookings and inquiries.`,
    },
    {
        id: "5",
        title: "AI Powered Search",
        slug: "seeklab",
        image: '/images/Projects/seeklabai.png',
        technology: "Webflow, Python, Node.js, custom ML models, NLP, Computer Vision, AWS",
        preview_url: "https://seeklab.ai/",
        short_description: `The platform leverages advanced machine learning to support text, voice, and image-based search, enabling users to find relevant products using natural language, photos, or spoken queries. SeekLab’s semantic search understands intent, handles typos and synonyms, and delivers personalized recommendations, helping reduce zero-result searches and improve conversions.`,
    },
    {
        id: "7",
        title: "Tucana Group",
        slug: "tucana",
        image: '/images/Projects/tucana.png',
        technology: "NextCloud, Windmill, Backbone.js, Python, Scripting",
        preview_url: "https://cloud-e.tucana-eng.com/",
        short_description: `Create scripts and a workflow in the Windmill app for Nextcloud. It manage file and folder approval, rejection, and locking for editing, with the ability to remove approval by specified user groups.`,
    },
    {
        id: "7",
        title: "ATA Fit",
        slug: "atafit",
        image: '/images/Projects/atafit.png',
        technology: "Joomla, Intercom, ActiveCampaign, Google Maps, GraphQL",
        preview_url: "https://www.ata.fit/trainer-map/",
        short_description: `This platform is a mission driven edu platform focused on delivering accessible fitness training resources and certification programs for adaptive and inclusive fitness professionals. This is designed to provide a smooth, responsive user experience with a strong emphasis on content accessibility and scalability.`,
    },
];

export default Project;