const Project = [
    {
        id: "1",
        title: "EASE - HIPAA Compliant App",
        slug: "easehipaa",
        image: '/images/Projects/ease-app.png',
        technology: "React Native, TypeScript,Firebase, GraphQL, TRPC",
        preview_url: "https://apps.apple.com/us/app/ease-applications-messaging/id838601897",
        short_description: `Ease, a HIPAA-compliant app, sends secure updates on patient status via text, photo, and video, improving communication and satisfaction for families. My role included adding group video calls, enhancing patient/contact workflows, enabling multi-patient updates, improving invites, and supporting surveys, branding, and push notifications.`,
    },
    {
        id: "2",
        title: "Teamly",
        slug: "teamly",
        image: '/images/Projects/react-1.png',
        technology: "React,Redux,Python,Django,Bootstrapr",
        preview_url: "https://www.teamly.com/",
        short_description: `Teamly is a team and workspace project management tool that works in role based hierarchy to manage permissions and tasks among a team. I have worked on implementing UI designs to match Figma, integrating with API using GraphQL, writing testable and reusable components, testing components using Cypress, and writing unit tests using JEST.`,
    },
    {
        id: "3",
        title: "iFit",
        slug: "ifit",
        image: '/images/Projects/nextjs-1.png',
        technology: "React,Next.js,Typescript,Tailwind CSS,SSR",
        preview_url: "https://www.ifit.com/",
        short_description: `Ifit is an interactive realtime workout and exercise guide system that brings you professional workouts and insight. I made extensive use of Next js to implement a responsive user interface with tailwindcss and have it load progressively over different screen sizes. I also built caching with redis for faster page loads.`,
    },
    {
        id: "4",
        title: "Overflow.io",
        slug: "overflowio",
        image: '/images/Projects/nextjs-2.png',
        technology: "React,Next.js,Node.js,D3.js,Tailwind CSS,AWS",
        preview_url: "https://overflow.io/",
        short_description: `My role heavily involved implementing React-Diagrams and D3.js, allowing for the creation of intricate, interactive diagrams essential for user flow visualization. Also, integrating Tailwind CSS enabled me to design a sleek, responsive user interface, aligning with the modern aesthetic needs of design teams.​`,
    },
    {
        id: "5",
        title: "Acorn-I",
        slug: "acorni",
        image: '/images/Projects/angular-1.png',
        technology: "Angular,Typescript,SCSS,Chart.js,Node",
        preview_url: "https://acorn-i.com/",
        short_description: `My primary focus was on implementing the front-end development using Angular, Chartjs, and styled-components. By seamlessly blending captivating design elements with responsive layouts, we ensured an exceptional user experience that captivated visitors and encouraged engagement.​`,
    },
    {
        id: "6",
        title: "Shopdolphinmall",
        slug: "shopdolphinmall",
        image: '/images/Projects/vue-1.png',
        technology: "Vue,Nuxt.js,Node,Vuetify,Netlify",
        preview_url: "https://shopdolphinmall.com/",
        short_description: `This project is a dynamic website designed to provide an immersive online shopping experience for customers of Dolphin Mall, a prominent shopping center. Working closely with a team of designers, UX/UI specialists, and backend developers, my primary responsibility was to leverage the power of Nuxt.js to build the front-end of the website.`,
    },
    {
        id: "7",
        title: "Breakthroughfuel",
        slug: "breakthroughfuel",
        image: '/images/Projects/gatsby-1.png',
        technology: "React,Gatsby,Node,MUI,PWA",
        preview_url: "https://www.breakthroughfuel.com/",
        short_description: `Breakthrough is a venture company that provides innovative transportation management technology and market insights to the world’s most reputable household brands. I have worked on implementing user interface components for the whole website. Also, I made them statically generated during build time using SSG(Server Side Generator) for faster page loads.`,
    },
    {
        id: "8",
        title: "Goingpublic",
        slug: "goingpublic",
        image: '/images/Projects/laravel-1.png',
        technology: "Python,Django,Vue.js,Vuex,Bootstrap",
        preview_url: "https://goingpublic.com/",
        short_description: `This is a platform that features news and articles related to companies that are going public or considering going public. On the front end, I leveraged Vue.js to create dynamic and interactive user interfaces. On the back end, I implemented secure user authentication, data storage, and server-side validation. Also, I built an admin dashboard page using Django.`,
    },
    {
        id: "9",
        title: "SBenekiva Core",
        slug: "sbenekivacore",
        image: '/images/Projects/benekiva.png',
        technology: "Angular,Node,Express,MongoDB,Azure",
        preview_url: "https://www.amishtables.com/",
        short_description: `This is the insurance claims management system I recently worked on. My role is to upgrade the Angular app to a modern version, refactor legacy code, and ensure backward compatibility via testing. I enhance API integration with the Express/Node.js backend while collaborating in an agile, cross-time-zone team.`,
    },
    {
        id: "10",
        title: "Adola AI",
        slug: "adolaai",
        image: '/images/Projects/adolaai.png',
        technology: "Node.js,LLM,OpenAI API,TypeScript,TailwindCSS",
        preview_url: "https://adola.ai/",
        short_description: `Adola transforms telephony by integrating AI voice assistants with phone systems. Adola offers AI assistants for various businesses like restaurants, dentists, mechanics, barbershops, lawyers, doctors, construction, and general service. It also provides outbound call services for surveys, lead qualification, and event promotion.`,
    },
    {
        id: "11",
        title: "Trading Education Platform",
        slug: "trendmonster",
        image: '/images/Projects/trendmonster.png',
        technology: "Next.js,FastAPI,Pine Script,Barchart API,Redis,Stripe,Docker,AWS",
        preview_url: "https://trend.goatacademy.org/",
        short_description: `This platform documents a live experiment using a proprietary trading methodology developed by experienced market practitioners, emphasizing transparency by showing real-time signals, trades, and outcomes. TrendMonster serves as a learning tool and demonstration of a systematic approach to capturing market trends and managing risk.`,
    },
    {
        id: "12",
        title: "Trip Planner using AI",
        slug: "triptile",
        image: '/images/Projects/triptile.png',
        technology: "React.js,Node.js,Maps APIs,Stripe",
        preview_url: "https://www.triptile.com/",
        short_description: `Online travel planning and booking platform that helps users design personalized multi-city itineraries and book travel arrangements in one place. The service lets travelers choose destinations, hotels, activities, and transportation to build custom trips across regions like Europe, Asia, and the Americas.`,
    },
    {
        id: "13",
        title: "Infinity Nail Spa & Salon",
        slug: "infinitytopeka",
        image: '/images/Projects/infinitytopeka.png',
        technology: "WordPress,SimpyBook.me,Divi,MySQL,Google Maps",
        preview_url: "https://www.infinitytopeka.com/",
        short_description: `The site is structured to clearly present service offerings, pricing information, and contact details, while enabling online appointment booking to streamline the customer journey. This platform emphasizes usability, responsive design, and conversion-focused layout to drive bookings and inquiries.`,
    },
    {
        id: "14",
        title: "AI Powered Search",
        slug: "seeklab",
        image: '/images/Projects/seeklabai.png',
        technology: "Webflow,Python,Node.js,ML models,NLP,Computer Vision,AWS",
        preview_url: "https://seeklab.ai/",
        short_description: `Seeklab leverages advanced machine learning to support text, voice, and image-based search, enabling users to find relevant products using natural language, photos, or spoken queries. SeekLab’s semantic search understands intent, handles typos and synonyms, and delivers personalized recommendations, helping reduce zero-result searches and improve conversions.`,
    },
    {
        id: "15",
        title: "ATA Fit",
        slug: "atafit",
        image: '/images/Projects/atafit.png',
        technology: "Joomla,Intercom,Google Maps, GraphQL",
        preview_url: "https://www.ata.fit/trainer-map/",
        short_description: `ATA Fit is a mission driven edu platform focused on delivering accessible fitness training resources and certification programs for adaptive and inclusive fitness professionals. This is designed to provide a smooth, responsive user experience with a strong emphasis on content accessibility and scalability.`,
    },
    {
        id: "16",
        title: "Mortgage CRM",
        slug: "mortgagecrm",
        image: '/images/Projects/mortgagecrm.png',
        technology: "React,TypeScript,Tailwind CSS",
        preview_url: "",
        short_description: `Built a CRM frontend interface used daily by a broker team to manage leads, collect documents, and follow recommended follow-ups with minimal manual effort. The user interface was implemented using React, TypeScript, and Tailwind CSS, with a strong focus on workflow efficiency, clarity, and auditability.`,
    },
];

export default Project;