const Skills = [
    {
        id: 7,
        slug: "JavaScript",
        title: "JavaScript",
        image: "/images/skills/javascript.svg",
        order: 1,
        created_at: "May 9 2023",
        updated_at: "May 9 2023",
    },
    {
        id: 7,
        slug: "TypeScript",
        title: "TypeScript",
        image: "/images/skills/typescript.svg",
        order: 1,
        created_at: "May 9 2023",
        updated_at: "May 9 2023",
    },
    {
        id: 7,
        slug: "Python",
        title: "Python",
        image: "/images/skills/python.svg",
        order: 1,
        created_at: "May 9 2023",
        updated_at: "May 9 2023",
    },
    {
        id: 7,
        slug: "Sass",
        title: "Sass",
        image: "/images/skills/sass.svg",
        order: 1,
        created_at: "May 9 2023",
        updated_at: "May 9 2023",
    },
    {
        id: 7,
        slug: "React.js",
        title: "React.js",
        image: "/images/skills/react.svg",
        order: 1,
        created_at: "May 9 2023",
        updated_at: "May 9 2023",
    },
    {
        id: 7,
        slug: "Next.js",
        title: "Next.js",
        image: "/images/skills/next.svg",
        order: 1,
        created_at: "May 9 2023",
        updated_at: "May 9 2023",
    },
    {
        id: 8,
        slug: "Svelte",
        title: "Svelte",
        image: "/images/skills/svelte.svg",
        order: 1,
        created_at: "May 9 2023",
        updated_at: "May 9 2023",
    },
    {
        id: 9,
        slug: "TailWindCss",
        title: "TailWindCSS",
        image: "/images/skills/tailwind.svg",
        order: 1,
        created_at: "May 9 2023",
        updated_at: "May 9 2023",
    },
    {
        id: 10,
        slug: "Three.js",
        title: "Three.js",
        image: "/images/skills/threejs.svg",
        order: 1,
        created_at: "May 9 2023",
        updated_at: "May 9 2023",
    },
    {
        id: 12,
        slug: "Node.js",
        title: "Node.js",
        image: "/images/skills/node.svg",
        order: 1,
        created_at: "May 9 2023",
        updated_at: "May 9 2023",
    },
    {
        id: 13,
        slug: "Express.js",
        title: "Express.js",
        image: "/images/skills/express.svg",
        order: 1,
        created_at: "May 9 2023",
        updated_at: "May 9 2023",
    },
    {
        id: 11,
        slug: "Django",
        title: "Django",
        image: "/images/skills/django.svg",
        order: 1,
        created_at: "May 9 2023",
        updated_at: "May 9 2023",
    },
    {
        id: 11,
        slug: "FastAPI",
        title: "FastAPI",
        image: "/images/skills/fastapi.svg",
        order: 1,
        created_at: "May 9 2023",
        updated_at: "May 9 2023",
    },
    {
        id: 11,
        slug: "Flask",
        title: "Flask",
        image: "/images/skills/flask.svg",
        order: 1,
        created_at: "May 9 2023",
        updated_at: "May 9 2023",
    },
    {
        id: 11,
        slug: "Laravel",
        title: "Laravel",
        image: "/images/skills/laravel.svg",
        order: 1,
        created_at: "May 9 2023",
        updated_at: "May 9 2023",
    },
    {
        id: 11,
        slug: "RestAPI",
        title: "Rest API",
        image: "/images/skills/rest.svg",
        order: 1,
        created_at: "May 9 2023",
        updated_at: "May 9 2023",
    },
    {
        id: 11,
        slug: "GraphQLAPI",
        title: "GraphQL API",
        image: "/images/skills/graphql.svg",
        order: 1,
        created_at: "May 9 2023",
        updated_at: "May 9 2023",
    },
    {
        id: 11,
        slug: "PostgreSQL",
        title: "PostgreSQL",
        image: "/images/skills/postgresql.svg",
        order: 1,
        created_at: "May 9 2023",
        updated_at: "May 9 2023",
    },
    {
        id: 14,
        slug: "Redis",
        title: "Redis",
        image: "/images/skills/redis.svg",
        order: 1,
        created_at: "May 9 2023",
        updated_at: "May 9 2023",
    },
    {
        id: 16,
        slug: "Rails",
        title: "Rails",
        image: "/images/skills/rails.svg",
        order: 1,
        created_at: "May 9 2023",
        updated_at: "May 9 2023",
    },
];

export default Skills;